App_Order/urls.py
from django.urls import path
from . import views

app_name='App_Order'

urlpatterns = [
    path('add_toCart/<pk>/',views.add_to_cart,name='add_toCart'),
    path('viewCart/',views.cart_view,name='viewCart'),
    path('checkout/',views.checkout,name='checkout'),
    path('increase/<pk>/',views.increase,name='increase'),
    path('decrease/<pk>/',views.decrease,name='decrease'),
]

App_Shop/urls.py
from django.urls import path
from . import views

app_name='App_Shop'

urlpatterns = [
    path('',views.createshop,name='shop_create'),
    path('add_product/',views.addproduct,name='add_product'),
    path('allproducts/',views.viewproducts,name='allproducts'),
    path('addtoshop/<pk>/',views.addtoshop,name='addtoshop'),
    path('viewproduct/<pk>/',views.ProductDetail.as_view(),name='viewproduct'),
]

e_commerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App_Login.urls')),
    path('shop/',include('App_Shop.urls')),
    path('order/',include('App_Order.urls')),
]

urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

App_Shop/models.py
from django.db import models
from App_Login.models import Seller
# Create your models here.




        
class Product(models.Model):
    mainimage=models.ImageField(upload_to='products')
    name=models.CharField(max_length=264)
    added_by=models.ForeignKey(Seller,on_delete=models.CASCADE)
    preview_text=models.TextField(max_length=100,verbose_name='Preview Text')
    detail_text=models.TextField(max_length=1000,verbose_name='Detail Text')
    price=models.FloatField()
    old_price=models.FloatField(default=0.00)
    created_at=models.DateTimeField(auto_now_add=True)
    added_to_shop=models.BooleanField(default=False)
    
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering=['-created_at',]
        verbose_name_plural='Products'
        
        
        
class ShopOwner(models.Model):
    owner=models.ForeignKey(Seller,on_delete=models.CASCADE,related_name='shop_owner')
    shop_title=models.CharField(max_length=150,blank=True)
    products=models.ManyToManyField(Product)
    shop_created=models.BooleanField(default=False)
    shop_description=models.CharField(max_length=255,blank=True)
    shop_date=models.DateTimeField(auto_now_add=True,blank=True)
    def __str__(self):
        return self.shop_title
    
    class Meta:
        verbose_name_plural='Owner'

App_Shop/forms.py
from . import models
from django import forms

class ShopCreator(forms.ModelForm):
    class Meta:
        model=models.ShopOwner
        fields=('shop_title','shop_description',)
    
class AddProducts(forms.ModelForm):
    class Meta:
        model=models.Product
        exclude=('added_by','added_to_shop',)

App_Shop/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404,render,HttpResponseRedirect
from django.urls import  reverse,reverse_lazy
from . import forms,models
from django.contrib.auth.decorators import login_required
from App_Login.models import Seller
from App_Login.decorators import seller
from django.views.generic import ListView,DetailView

from django.contrib.auth.mixins import LoginRequiredMixin

class ProductDetail(DetailView,LoginRequiredMixin):
    model=models.Product
    template_name='App_Shop/productdetail.html'
    context_object_name='product'    
    

# Create your views here.
@login_required
@seller()
def createshop(request):
    user=get_object_or_404(Seller,user=request.user)
    shop=models.ShopOwner.objects.filter(owner=user)
    if shop.exists():
        shop=shop[0]
    form=forms.ShopCreator()
    if request.method=='POST':
        form=forms.ShopCreator(request.POST) 
        if form.is_valid():
            shopform=form.save(commit=False)
            shopform.owner=user
            shopform.shop_created=True
            shopform.save()
            messages.success(request, 'Shop Created Succesfully')
            return HttpResponseRedirect(reverse('App_Shop:shop_create'))
    return render(request,'App_Shop/shop.html',context={'form':form,'shop':shop})


@login_required
@seller()
def addproduct(request):
    user=get_object_or_404(Seller,user=request.user)
    form=forms.AddProducts()
    if request.method=='POST':
        form=forms.AddProducts(request.POST,request.FILES) 
        if form.is_valid():
            productform=form.save(commit=False)
            if 'mainimage'in request.FILES:          #Applies for all kind of files pdf,doc,etc. 
                productform.mainimage=request.FILES['mainimage']
            productform.added_by=user
            productform.save()
            messages.success(request, 'Product Added Succesfully')
            return HttpResponseRedirect(reverse('App_Login:home'))
    return render(request,'App_Shop/productadd.html',context={'form':form})


@login_required
@seller()
def viewproducts(request):
    user=get_object_or_404(Seller,user=request.user)
    shop=models.ShopOwner.objects.get(owner=user,shop_created=True)
    shop_products=shop.products.all()
    user_products=models.Product.objects.filter(added_by=user,added_to_shop=False)
    return render(request,'App_Shop/products.html',context={'shop':shop,'user_products':user_products,'shop_products':shop_products})
    
    
@login_required
@seller()
def addtoshop(request,pk):
    user=get_object_or_404(Seller,user=request.user)
    shop=models.ShopOwner.objects.get(owner=user,shop_created=True)
    user_products=models.Product.objects.filter(added_by=user,pk=pk,added_to_shop=False)
    if user_products.exists():
        user_products=user_products[0]
    shop.products.add(user_products)
    user_products.added_to_shop=True
    user_products.save()
    shop.save()
    messages.success(request, 'Added to Shop Succesfully')
    return HttpResponseRedirect(reverse('App_Login:home'))

templates/App_Shop/productadd.html
{% extends "Base.html" %}
{% load crispy_forms_tags %}
{% block title_block %}
  Add Products
{% endblock title_block %}

{% block body_block %}
  
<h1 class="text-center my-5">Add Products</h1>
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
  {{form|crispy}}
<input type="submit" value="Add Product" class="btn btn-outline-dark w-100 my-4">
</form>


{% endblock body_block %}

templates/App_Shop/productdetail.html
{% extends "Base.html" %}
{% load crispy_forms_tags %}

{% block body_block %}

<!-- {{product.name}} -->

<div class="card my-5">
    <div class="row g-0">
      <div class="col-md-4">
        <img src="/media/{{product.mainimage}}" style="width:100%;height:100%;object-fit:cover" alt="...">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title my-2">{{product.name}}</h5>
          <p class="card-text text-warning my-2" style="font-size: 24px;">BDT &#2547;{{product.price|floatformat:"0"}}</p>
          <p style="font-size: 21px; margin-bottom:15px"><strong>Seller: </strong> {{product.added_by.user.username}} </p>
          <h6 style="font-size: 28px; margin-bottom:15px">Description: </h6>
          <p class="card-text my-2" >{{product.detail_text|linebreaks}}</p>
          <a href="{% url 'App_Order:add_toCart' pk=product.pk %}" class="my-3 btn btn-info">Add To Cart</a>
          <p class="card-text my-2"><small class="text-muted">Added at : {{product.created_at|date:"D d M Y"}}</small></p>
        </div>
      </div>
    </div>
  </div>
{% endblock  %}

templates/App_Shop/products.html
{% extends "Base.html" %}
{% load crispy_forms_tags %}
{% block title_block %}
Add To Shop
{% endblock title_block %}

{% block body_block %}

<h1 class="text-center my-5">Add Products to Shop</h1>

<div class="row">

  <div class="col-md-6">
    {% for product in shop_products  %}
    <table class="table table-hover mt-5 table-borderless table-sm">
      <caption> Products </caption>
      <thead>
        <tr>
          <th scope="col">Serial</th>
          <th scope="col">Product</th>
          <th scope="col">Old Price</th>
          <th scope="col">New Price</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">{{forloop.counter}}</th>
          <td>{{product.name}}</td>
          <td>{{product.old_price}}</td>
          <td>{{product.price}}</td>
        </tr>
      </tbody>
      </table>
      {%empty%}
      <h2>No Products In the Shop</h2>
      {% endfor %}

  </div>
  <div class="col-md-6">
    {% for product in user_products %}
    <table class="table table-hover mt-5 table-borderless table-sm">
      <caption> Products </caption>
      <thead>
        <tr>
          <th scope="col">Serial</th>
          <th scope="col">Product</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">{{forloop.counter}}</th>
          <td>{{product.name}}</td>
          <td>{{product.option1}}</td>
          <td><a href="{% url 'App_Shop:addtoshop' pk=product.pk %}" class="btn btn-info">Add To Shop</a></td>
        </tr>
      </tbody>
      {%empty%}
      <h2> No Products to Add To the Shop </h2>
      {% endfor %}
    </table>
  </div>
</div>

{% endblock body_block %}

templates/App_Shop/shop.html
{% extends "Base.html" %}
{% load crispy_forms_tags %}
{% block title_block %}
Shop
{% endblock title_block %}

{% block body_block %}
{% if not shop.shop_created %}
<p>{{shop.shop_created}}</p>
<h1 class="text-center my-5">No Shops to show</h1>
<form method="post">
  {% csrf_token %}
  {{form|crispy}}
  <input type="submit" value="Create Shop" class="btn btn-outline-dark w-100 my-4">
</form>
{% else %}
<h1 class="text-center my-5">Shops</h1>
<div class="card w-100">
  <div class="card-header">
    <h3 class="my-3">{{shop.shop_title}}</h3>
  </div>
  <div class="card-body">
    <h4 class="card-text my-3">{{shop.shop_description}}</h4>
    <a href="{% url 'App_Shop:allproducts' %}" class="btn btn-warning btn-sm">Go To Store</a>
  </div>
  <div class="card-footer">
    <h5>Created At: {{shop.shop_date|date:"D d M Y"}}</h5></div>
</div>


{% endif %}
{% endblock body_block %}