App_Login/urls.py
from django.urls import path
from . import views

app_name='App_Login'

urlpatterns = [
    path('',views.index,name='home'),
    path('customer_signup/',views.customer_signup_view,name='csignup'),
    path('seller_signup/',views.seller_signup_view,name='ssignup'),
    path('login/',views.login_view,name='login'),
    path('customer_update/',views.c_profilechange,name='customer_profile_update'),
    path('seller_update/',views.s_profilechange,name='seller_profile_update'),
    path('logout/',views.logout_view,name='logout'),
]

App_Order/urls.py
from django.urls import path
from . import views

app_name='App_Order'

urlpatterns = [
    path('add_toCart/<pk>/',views.add_to_cart,name='add_toCart'),
    path('viewCart/',views.cart_view,name='viewCart'),
    path('checkout/',views.checkout,name='checkout'),
    path('increase/<pk>/',views.increase,name='increase'),
    path('decrease/<pk>/',views.decrease,name='decrease'),
]

App_Shop/urls.py
from django.urls import path
from . import views

app_name='App_Shop'

urlpatterns = [
    path('',views.createshop,name='shop_create'),
    path('add_product/',views.addproduct,name='add_product'),
    path('allproducts/',views.viewproducts,name='allproducts'),
    path('addtoshop/<pk>/',views.addtoshop,name='addtoshop'),
    path('viewproduct/<pk>/',views.ProductDetail.as_view(),name='viewproduct'),
]

e_commerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App_Login.urls')),
    path('shop/',include('App_Shop.urls')),
    path('order/',include('App_Order.urls')),
]

urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

App_Order/models.py
from django.db import models
from App_Login.models import Customer
from App_Shop.models import Product

# Create your models here.
class Cart(models.Model):
    user=models.ForeignKey(Customer,on_delete=models.CASCADE,related_name='customer')
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    added_time=models.DateTimeField(auto_now_add=True)
    purchased=models.BooleanField(default=False)
    
    def __str__(self):
        return f'{self.product} X {self.quantity}'
    
    def get_total(self):
        return float(self.product.price*self.quantity)
    
    
    
class Order(models.Model):
    user=models.ForeignKey(Customer,on_delete=models.CASCADE)
    cart_items=models.ManyToManyField(Cart)
    added_at=models.DateTimeField(auto_now_add=True)
    ordered=models.BooleanField(default=False)
    couponcode=models.CharField(max_length=100,blank=True)
    
    def get_total_price(self):
        total=0
        for i in self.cart_items.all():
           total+=float(i.get_total())
        return total 
    
    
    

App_Order/views.py
from django.shortcuts import render, get_object_or_404, redirect


from django.contrib.auth.decorators import login_required

from django.contrib import messages

from . import models
from App_Shop.models import Product
from App_Login.models import Customer
from App_Login.decorators import customer

# Create your views here.
@login_required
@customer()
def add_to_cart(request, pk):
    product = get_object_or_404(Product, pk=pk)
    customer = get_object_or_404(Customer, user=request.user)
    print(product)
    cart = models.Cart.objects.get_or_create(
        product=product, user=customer, purchased=False)
    print(cart)
    order = models.Order.objects.filter(user=customer, ordered=False)
    if order.exists():
        order = order[0]

        if order.cart_items.filter(product=product).exists():
            cart[0].quantity += 1
            cart[0].save()
            messages.success(request, 'Cart Updated Succesfully')
        else:
            order.cart_items.add(cart[0])
            order.save()
            messages.success(request, 'Item Added to Cart Succesfully')
    else:
        order = models.Order(user=customer)
        order.save()
        order.cart_items.add(cart[0])
        order.save()
        messages.success(
            request, 'Cart was Created Succesfully and Item Added')
    return  redirect("App_Order:viewCart")

@login_required
@customer()
def cart_view(request):
    customer = get_object_or_404(Customer, user=request.user)
    carts = models.Cart.objects.filter(user=customer, purchased=False)
    orders = models.Order.objects.filter(user=customer, ordered=False)
    if carts.exists() and orders.exists():
        order = orders[0]
        return render(request, 'App_Order/Cart.html', context={'order': order,'cart':carts})
    else:
        messages.warning(request, "You Dont Have Any Items in The Cart")
        return redirect("App_Login:home")
    

@login_required
@customer()
def increase(request,pk):
    customer = get_object_or_404(Customer, user=request.user)
    product = get_object_or_404(Product, pk=pk)
    # carts = models.Cart.objects.filter(user=customer, purchased=False)
    orders = models.Order.objects.filter(user=customer, ordered=False)
    if orders.exists():
        order=orders[0]
        if order.cart_items.filter(product=product).exists():
            cart=models.Cart.objects.filter(product=product,user=customer,purchased=False)
            cart=cart[0]
            if cart.quantity>=1:
                cart.quantity+=1
                cart.save()
                messages.success(request,'Item Increased Succesfully')
            else:
                messages.warning(request, "You Dont Have this item in The Cart")
                return redirect("App_Login:home")

    return  redirect("App_Order:viewCart")


@login_required
@customer()
def decrease(request,pk):
    customer = get_object_or_404(Customer, user=request.user)
    product = get_object_or_404(Product, pk=pk)
    # carts = models.Cart.objects.filter(user=customer, purchased=False)
    orders = models.Order.objects.filter(user=customer, ordered=False)
    if orders.exists():
        order=orders[0]
        if order.cart_items.filter(product=product).exists():
            cart=models.Cart.objects.filter(product=product,user=customer,purchased=False)
            cart=cart[0]
            if cart.quantity>1:
                cart.quantity-=1
                cart.save()
                messages.warning(request, "Quantity Decreased...")
            else:
                order.cart_items.remove(cart)
                cart.delete()
                messages.warning(request, "You Dont Have this item in The Cart")
                return redirect("App_Login:home")

    return  redirect("App_Order:viewCart")


@login_required
@customer()
def checkout(request):
    customer = get_object_or_404(Customer, user=request.user)
    orders = models.Order.objects.filter(user=customer, ordered=False)
    if orders.exists():
        order=orders[0]
        cart=models.Cart.objects.filter(user=customer,purchased=False)[0]
        order.ordered=True
        cart.purchased=True
        order.save()
        cart.save()
        messages.success(request, "Checkout Successfull")
    else:
        messages.warning(request, "Add Someitems to checkout")
        return redirect("App_Login:home")
    
    return redirect("App_Login:home")

templates/App_Order/Cart.html
{% extends "Base.html" %}
{% load crispy_forms_tags %}

{% block body_block %}

<div class="container my-5">
    <h1 class='mb-5 text-center'>Your Cart Total &#2547; {{order.get_total_price|floatformat:2}}</h1>
    <table class="table table-hover table-borderless my-2">
        <thead class="table-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Product Name</th>
                <th scope="col">Quantity</th>
                <th scope="col">Price</th>
            </tr>
        </thead>
        <tbody>
            {% for cart in cart %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{cart.product.name}}</td>
                <td>
                    <a href="{% url 'App_Order:decrease' pk=cart.product.pk %}"><span
                            class="badge bg-dark text-light mr-2"> - </span></a>
                    {{cart.quantity}}
                    <a href="{% url 'App_Order:increase' pk=cart.product.pk %}"><span
                            class="badge bg-dark text-light ml-2"> + </span></a>
                </td>
                <td>&#2547; {{cart.get_total|floatformat:2}}</td>
            </tr>
            {% endfor %}
            <tr class='my-3'>
                <td colspan='3'>
                    <h5 class="text-center"> Total </h5>
                </td>
                <td colspan='2' >&#2547; {{order.get_total_price|floatformat:2}}</td>
            </tr>
            <tr>
                <td colspan="3"></td>
                <td ><a href="{% url 'App_Order:checkout' %}" class='btn btn-info ml-auto'>Proceed to
                        Checkout</a></td>
                <td rowspan="1" ><a href="{% url 'App_Login:home' %}" class='btn btn-warning ml-auto'>Continue Shopping</a>
                </td>
            </tr>

        </tbody>
    </table>

    {% endblock  %}

templates/App_Order/CheckOutPage.html
{% extends "Base.html" %}
{% load crispy_forms_tags %}

{% block body_block %}


<h1 class="text-center my-5">Checkout Succesfully Completed <br> Thank You </h1>

{% endblock  %}