App_Login/urls.py
from django.urls import path
from . import views

app_name='App_Login'

urlpatterns = [
    path('',views.index,name='home'),
    path('customer_signup/',views.customer_signup_view,name='csignup'),
    path('seller_signup/',views.seller_signup_view,name='ssignup'),
    path('login/',views.login_view,name='login'),
    path('customer_update/',views.c_profilechange,name='customer_profile_update'),
    path('seller_update/',views.s_profilechange,name='seller_profile_update'),
    path('logout/',views.logout_view,name='logout'),
]

App_Order/urls.py
from django.urls import path
from . import views

app_name='App_Order'

urlpatterns = [
    path('add_toCart/<pk>/',views.add_to_cart,name='add_toCart'),
    path('viewCart/',views.cart_view,name='viewCart'),
    path('checkout/',views.checkout,name='checkout'),
    path('increase/<pk>/',views.increase,name='increase'),
    path('decrease/<pk>/',views.decrease,name='decrease'),
]

App_Shop/urls.py
from django.urls import path
from . import views

app_name='App_Shop'

urlpatterns = [
    path('',views.createshop,name='shop_create'),
    path('add_product/',views.addproduct,name='add_product'),
    path('allproducts/',views.viewproducts,name='allproducts'),
    path('addtoshop/<pk>/',views.addtoshop,name='addtoshop'),
    path('viewproduct/<pk>/',views.ProductDetail.as_view(),name='viewproduct'),
]

e_commerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App_Login.urls')),
    path('shop/',include('App_Shop.urls')),
    path('order/',include('App_Order.urls')),
]

urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/Base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>
        {% block title_block %}
        E-Commerce Website
        {% endblock title_block %}


    </title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'App_Login:home' %}">M-Ecommerce</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'App_Login:home' %}">Home</a>
                    </li>
                    {%  if user.is_authenticated and user.is_customer %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'App_Login:customer_profile_update' %}">Customer Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'App_Order:viewCart'%}">Cart</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'App_Login:logout' %}">Logout</a>
                    </li>
                    {% elif user.is_authenticated and user.is_seller %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'App_Login:seller_profile_update' %}">Seller Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'App_Shop:shop_create' %}">Shop</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'App_Shop:add_product' %}">Add Products</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'App_Login:logout' %}">Logout</a>
                    </li>
                    {% elif user.is_authenticated and user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="">Admin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'App_Login:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'App_Login:csignup' %}">Customer SignUp</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'App_Login:ssignup' %}">Seller Signup</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'App_Login:login' %}">Login</a>
                    </li>

                    {% endif %}


            </div>
        </div>
    </nav>

    {% if messages %}
    {% for message in messages %}
    <div {% if message.tags %} class="alert alert-{{message.tags}} alert-dismissible fade show {% endif %}"
        role="alert">
        {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">&times;</button>
    </div>
    {% endfor %}
    {% endif %}

    <div class="container">
        {% block body_block %}

        {% endblock body_block %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous">
    </script>

</body>

</html>

templates/Home.html
{% extends "Base.html" %}
{% load crispy_forms_tags %}
{% block title_block %}
Home
{% endblock title_block %}


{% block body_block %}

<div class="row row-cols-1 row-cols-md-3 g-2 my-5">
  {% for product in product %}
  <div class="col">
    <div class='card'>
      <img src="/media/{{product.mainimage}}" alt="{{product.name}}" class="card-img-top">
      <div class="card-body">
        <h5>{{product.name}}</h5>
        <p class="card-text">{{product.preview_text}}</p>
        <a href="{% url 'App_Shop:viewproduct' pk=product.pk %}" class="btn btn-warning my-3">See More</a>
        <div>
          <div class='card-footer'>
            <span>&#2547; {{product.price|floatformat:2}}</span> &nbsp;&nbsp;&nbsp;&nbsp;
            <span style="text-decoration: line-through;">&#2547; {{product.old_price|floatformat:2}}</span>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock body_block %}